name = "echo"
version = "1.0.0"
licences = ["Apache-2.0"]
description = "A tiny echo server written in Gleam!"

repository = { type = "github", user = "gleam-lang", repo = "example-echo-server" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = "~> 0.18"
gleam_http = "~> 2.0"
gleam_elli = "~> 0.3"
gleam_erlang = "~> 0.7"

[dev-dependencies]
gleeunit = "~> 0.1"
